platform :ios,:deployment_target => "7.0"

pod 'WSCoachMarksView'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'Base64nl'
pod 'LDProgressView', '>= 1.1'
pod 'MJRefresh'
pod 'BlurImageProcessor'
pod 'AFNetworking'
pod 'UPStackMenu'
pod 'FXBlurView', '~> 1.6.3'
pod 'UIImage+RTTint'
pod 'FlatUIKit'
pod 'JSAnimatedImagesView'
pod 'GraphKit'
